### ISSUE TITLE
RESTful 相關問題

### ISSUE THREAD

**Issue by Knovour** [7a6163/gelovery-frontend#3]
- request 的錯誤是否是非 2xx 的 response？
- `src/mixins/responseError.vue` 裡的 `error.status`、`error.message` 是包含在回傳的資料裡嗎？
- 7-11 的送貨 API 跟提供的變數不符，我需要確定實際的 path 是什麼，真正需要的是哪一邊的變數
![截圖 2023-09-13 下午9 09 52](https://github.com/7a6163/gelovery-frontend/assets/893846/6e8900b0-1d1a-4caa-81f7-99d0e10f31f2)
![截圖 2023-09-13 下午11 23 01](https://github.com/7a6163/gelovery-frontend/assets/893846/8ddcfb71-ab4f-432e-b436-5761c7934028)
- 那個超長的 API 的變數是不是真的有那個斜槓？
![截圖 2023-09-13 下午9 41 28](https://github.com/7a6163/gelovery-frontend/assets/893846/9bcd75ee-8446-4cb5-887b-43cfceb915f9)
![截圖 2023-09-13 下午9 42 30](https://github.com/7a6163/gelovery-frontend/assets/893846/38939a5d-c1d1-4d7f-b92a-b4af385f80f6)

**Comment by 7a6163** [comment]
* 那個超長的 API 的變數是不是真的有那個斜槓？
這個是 電子發票手機載具的條件，這個 API 是去驗證他是不是真實的載具
![image](https://github.com/7a6163/gelovery-frontend/assets/579103/427471c3-7b5d-41d8-b7c0-5272ecc77ce6)

**Comment by 7a6163** [comment]
* request 的錯誤是否是非 2xx 的 response？
有 2xx 的 Response，我有用 401,404 之類的 http status
